config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users
  resources :answers

  resources :questions

  root 'home#index'
   get '/questions/:id' =>'home#question'   
   

   

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	include HasGravatar
	belongs_to :question

end

app/models/concerns/has_gravatar.rb
module HasGravatar

	def gravatar
		"http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
	end
end

app/models/question.rb
class Question < ActiveRecord::Base

	include HasGravatar

	has_many :answers
	
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	
	def create
		question = Question.find(params[:answer][:question_id])
		question.answers.create(answer_params)
		redirect_to question
	end
	
	private
	def answer_params
		params.require(:answer).permit(:email, :body)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user! , except: [ :index ]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@questions=Question.order(created_at: :desc).page(params[:page]).per(5).where("body LIKE ?","%#{params[:search]}%")
		@count_questions= Question.count
			
	end

	private
	def question_params
		params.require(:question).permit(:email, :body)		
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	
	def create
		Question.create(question_params)

		session[:current_user_email]= question_params[:email]
		redirect_to root_path
	end

	def show
		@question=Question.find(params[:id])
		@answers = @question.answers.order(created_at: :desc)
		@count= @question.answers.count
	end

	private

	def question_params
		params.require(:question).permit(:email, :body)
		
	end

	
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

def current_user_email
	session[:current_user_email]
end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navbar.html.erb

  <!--navbar-->
  	<nav class="navbar nav ">
    		<div class="container-fluid">
    			<div class="navbar-header">
    				<button type="button" class="navbar-toggle collapse" data-target="#bs-example-navbar-collapse-1">
    					<span class="sr-only"></span>
    					<span class="icon-bar"></span>
    					<span class="icon-bar"></span>
    					<span class="icon-bar"></span>
    				</button>
    				  <h5><a class=" navbar-brand askonebtn" href="/" >--askOne--</a></h5>
    			</div>
    		
    		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    			<ul class="nav navbar-nav navbar-right">
            <li class="nav navbar-text ">
            <h5></h5>
            </li> 
    				
    			</ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><button href="#" class="btn btn-danger navbar-btn btn-sm" data-toggle="modal" data-target="#question-modal">Ask a Question</a></button></li>
               <li class="dropdown dropdown-margin">
                <h5  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email%><span class="caret"></span></h5>
                <ul class="dropdown-menu">
                    <li><%= link_to "Edit profile", edit_user_registration_path%></li>
                    <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
          </li>
          <!--<li><%= link_to "Login", new_user_session_path, class: "btn btn-success navbar-btn btn-sm btn-login-join" %></li>
              <li><%= link_to "Join", new_user_registration_path, class: "btn btn-success navbar-btn btn-sm btn-login-join" %></li>-->
            <%else%>
              
            <%end%>
            
            
            
          </ul>
    		</div>
    		</div>
  	</nav>
  	<!--navbar-->
   

app/views/home/_new_answer_form.html.erb

  <div class="modal fade" id="new-answer-modal" tabindex="-1"role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">New Answer</h4>
        </div>
         
        <%= form_for :answer , url: '/answers' do |f| %>
          <input type="hidden" name="answer[question_id]"  value="<%= @question.id%>">
          <div class="modal-body">
            <div class="form-group">
              <%= f.label :email, class: "control-label" %>
              <%= f.text_field :email, value: current_user.email,required: true, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :Answer, class: "control-label" %>
              <%= f.text_area :body,required: true, class: "form-control" %>
            </div>
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit "Submit",  class: "btn btn-primary" %>
         </div>
      <% end %>
      </div>
    </div>
  </div>

app/views/home/_new_question_form.html.erb
  <div class="modal fade" id="question-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="exampleModalLabel">New question</h4>
        </div>
        <%= form_for :question, url: '/questions' do |f| %>
          <div class="modal-body">
              <div class="form-group">
                <%= f.label :email, class: "control-label" %>
                <%= f.text_field :email, required: true, class: "form-control"%>
              </div>
              <div class="form-group">
                <%= f.label :Question, class: "label-control"%>
                <%= f.text_area :body,required: true, class: "form-control" %>
              </div>       
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.submit "Submit", class: "btn btn-primary"%>
          </div>
        <%end%>
      </div>
    </div>
  </div>

app/views/home/index.html.erb
      <% if user_signed_in? %>
      <div class="container"> 	
        <div class="container ">
          <h4 class= 'title align'>"Ask questions about coding and web dev in general"</h4>
        <div class="row ">
          <!--search-->
          <div class="col-xs-6 col-sm-4 align-search">
            <div class="row">
              <%= form_tag root_path, :method => 'get' do %>
              <div class="col-lg-6">
                <div class="input-group">
                  <%= text_field_tag :search, params[:search], class: "well" %>
                  <span class="input-group-btn">
                    <%= submit_tag "Search", class: "btn btn-default well"%>
                  </span>
                </div><!-- /input-group -->
              </div><!-- /.col-lg-6 -->
              <% end %>

            </div><!-- /.row -->
            <!--<h4><a href="">Advaced search</a></h4>-->
          </div>
          <!--/search-->
          
          <div class="col-xs-6 col-sm-4">
            
          </div>
          <div class="col-xs-6 col-sm-4">
            
          </div>
        </div>
       </div>
      <div class="panel-body">
        <!--media object-->
        <% @questions.each do |q|%>
        <div class="media border">
          <div class="media-left media-middle">
            <a href="#">
              <img class="media-object" src="<%= q.gravatar %>">
            </a>
          </div>
          <div class="media-body">         
            <h3 class="media-heading email"><%= q.email%></h3>
            <h4 class="asked">Asked:</h4>
              <h4 ><span><%= q.body %> </span></h4>
              <div class='time-ago'><%= time_ago_in_words q.created_at %> ago</div>
             <a href="<%= question_path(q)%>" class="btn btn-success btn-xs">View answers</a>
         </div>
       </div>
       <!--media object-->    
       <% end %>
       <%if  @questions.empty?%>
        <div class="alert alert-info">Nothing yet here, please ask a question</div>
       <%end%>
     </div>
     <!--pagination-->
     <!--<div class="pager"><%= %></div>will_paginate @questions-->
     <div><%= paginate @questions %></div>
  <!--/pagination-->

     </div>
      <%else%>
        
        <div class="jumbotron center">
          <h2>AskOne</h2>
          <p>AskOne is a web app to make questions about coding and web development in general.</p>
            <%= link_to 'Login', new_user_session_path, class: "btn btn-sm btn-primary"%>
            <%= link_to 'Join', new_user_registration_path, class: "btn btn-sm btn-default"%>
        </div>
      <%end%>
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proy4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render'home/navbar'%>	
	<div class="container">
		<% flash.each do |name, msg|%>
		<%= content_tag(:div, msg, class: "alert alert-success")%>
		<%end%>
<%= yield %>
	 <%= render 'home/new_question_form'%>
	  
	
	</div>
</body>
</html>

app/views/questions/show.html.erb
  <%if user_signed_in?%>
    <div class="container">
    <div class="lead well">
      <div class="media">
        <div class="media-left">
          <a href="#">
            <img src="<%= @question.gravatar %>" alt="" class="media-object">
            </a>
        </div>
        
        <div class="media-body">
          <span class="label label-danger count"><h5>Answers: <%=@count%></h5></span> 
          <h4 class="media-heading"><%= @question.email%>  </h4>
         <h3>Asked:</h3>
        </div>
      </div>
       <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
        <%=@question.body%>  
        </a>        
      </h4>
    </div>
    
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
          <!--media object-->
          <% @answers.each do|answer|%>
            <div class="media">
              <div class="media-left media-middle">
                <a href="#">
                 <img src="<%=answer.gravatar %>" alt="" class="media-object">
                </a>
              </div>
              <div class="media-body">
                <h4 class="media-heading"><%= answer.email%> Answered:</h4>
                <h5><%= time_ago_in_words answer.created_at %> ago</h5> 
                <h3><%=answer.body%></h3>
              </div>
            </div>
            <%end%>
            <% if @answers.empty?%>
              <div class="alert alert-info">Nothing yet here,be the first to answer this question</div>
            <%end%>
          <!--media object-->
          <div>
              <form><a href="#" class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#new-answer-modal">New answer</a></form>
          </div>
      </div>
    </div>
  </div>
</div>
<div >
  <%= render 'home/new_answer_form'%>

</div>
    </div>
   
  </div>
  
  <%else%>
  <h5>Please login</h5>
  <%end%>
  